classDiagram
namespace m2gui {
  class Model
  class SignalMessage
  class SignalControl
}

Model *-- SignalStatus : emit()

TabDefault *-- Model
TabDefault <|-- TabOverview

TabOverview --> SignalMessage : connect()
TabOverview --> SignalControl : connect()
TabOverview --> SignalStatus : connect()
