classDiagram
namespace m2gui {
  class Model
  class SignalIlcStatus
}

Model *-- SignalIlcStatus : emit()

TabDefault *-- Model
TabDefault <|-- TabIlc
TabDefault <|-- TabIlcStatus

TabIlcStatus "1" *-- "84" TabIlc

TabIlcStatus --> SignalIlcStatus : connect()
