classDiagram
namespace m2gui {
  class Model
  class UtilityMonitor
  class SignalDetailedForce
}

Model *-- UtilityMonitor
UtilityMonitor *-- SignalDetailedForce : emit()

TabDefault *-- Model
TabDefault <|-- TabHardpointSelection

TabHardpointSelection --> SignalDetailedForce : connect()
